# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca99b24addeb280da2c3c9f2cd224e214a6535d8daca442456036d5f2282a6261f3f02ac14dac87cf853ec307eede4bc6445d31f7df4f6a01486af44663e2a1

test:
  secret_key_base: 38cf6cc0a04486929c52a38980d72d5e3231cee3026294a8f41d0385808d5ce20ab58fd3cb2097cd7fbb19d0f055894de8987787aeccfda7a8cefb2958ade029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
